### PR TITLE
test: transcript version IT

### PR DESCRIPTION
**Pull request by Miaritiana**

### CODE REVIEW

**Review by Miaritiana — COMMENTED** [review]
@NyH1409

**Review by NyH1409 — CHANGES_REQUESTED** [review]
Use crupdateTranscripts as operationId instead of crudStudentTranscripts
Screenshot from 2023-08-02 07-50-58

**Review by Miaritiana — COMMENTED** [review]
@NyH1409  it's done!
And for the integration test ?

**Comment by NyH1409** [comment]
> @NyH1409 it's done! And for the integration test ?

It's ok but as I've already mentioned, use static import when asserting

**Review by NyH1409 — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
